### ISSUE TITLE
Fix Check Data Matching page

### ISSUE THREAD

**Issue by EvgenyKarataev** [ColFusion/ColfusionWeb#33]
Currently Check Data Matching page doesn't show any values and throws exceptions.

Error messages in browser console:

```
http://192.168.33.10/dataMatchChecker/getDataTables.php?timestamp=1442761150139 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2015-09-20 10:59:10.234 http://192.168.33.10/dataMatchChecker/getDataTables.php?timestamp=1442761150158 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2015-09-20 10:59:10.262 http://192.168.33.10/dataMatchChecker/getDataTables.php?timestamp=1442761150179 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2015-09-20 10:59:12.055 http://192.168.33.10/dataMatchChecker/getDataTables.php?timestamp=1442761152017 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2015-09-20 10:59:12.073 http://192.168.33.10/dataMatchChecker/getDataTables.php?timestamp=1442761152031 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2015-09-20 10:59:12.097 http://192.168.33.10/dataMatchChecker/getDataTables.php?timestamp=1442761152039 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Exception in php/apache error.log:

```
[Sun Sep 20 14:59:12.175456 2015] [:error] [pid 10073] [client 192.168.33.1:58939] PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /Colfusion/DAL/ExternalDBHandlers/MSSQLHandler.php:19\nStack trace:\n#0 /Colfusion/DAL/ExternalDBHandlers/MSSQLHandler.php(19): PDO->__construct('dblib:dbname=co...', 'remoteUserTest', 'pass')\n#1 /Colfusion/DAL/ExternalDBHandlers/MSSQLHandler.php(145): MSSQLHandler->getConnection()\n#2 /Colfusion/dataMatchChecker/DataMatchExecutor.php(69): MSSQLHandler->ExecuteQuery('select value as...')\n#3 /Colfusion/dataMatchChecker/DataMatcher.php(23): DataMatchExecutor->CheckDataMatching(Object(DataMatcherLinkOnePart), Object(DataMatcherLinkOnePart))\n#4 /Colfusion/dataMatchChecker/getDataTables.php(51): DataMatcher->CheckDataMatching(Object(DataMatcherLinkOnePart), Object(DataMatcherLinkOnePart))\n#5 /Colfusion/dataMatchChecker/getDataTables.php(44): getDifferentAndSameValueTables(Object(DataMatcherLinkOnePart), Object(DataMatcherLinkOnePart))\n#6 {main}\n  thrown in /Colfusion/DAL/ExternalDBHandlers/MSSQLHandler.php on line 19, referer: http://192.168.33.10/dataMatchChecker/dataMatchChecker.php
```

**Comment by EvgenyKarataev** [comment]
For now I will just hide the button that leads to the data matching page.
